---
- name: Prepare the devops environment
  hosts: openstack
  become: yes
  roles:
   - common

- name: Configure control node iptables rule
  hosts: Controller
  become: yes
  roles:
   - control_node
